export const ROUTES = {
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:slug",
  CATEGORY: "/category/:slug",
  SEARCH: "/search",

  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",

  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER_SUCCESS: "/order/success",
  ORDER_HISTORY: "/orders",
  ORDER_DETAIL: "/orders/:orderId",
  PROFILE: "/profile",
  WISHLIST: "/wishlist",
  MEMBERSHIP: "/membership",

  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCT_CREATE: "/admin/products/create",
  ADMIN_PRODUCT_EDIT: "/admin/products/:id/edit",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_BRANDS: "/admin/brands",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_ORDER_DETAIL: "/admin/orders/:orderId",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAIL: "/admin/users/:userId",
  ADMIN_EMPLOYEES: "/admin/employees",
  ADMIN_EMPLOYEE_DETAIL: "/admin/employees/:employeeId",
  ADMIN_PROMOTIONS: "/admin/promotions",
  ADMIN_REPORTS: "/admin/reports",

  STAFF: "/staff",
  STAFF_DASHBOARD: "/staff/dashboard",
  STAFF_ORDERS: "/staff/orders",
  STAFF_ORDER_DETAIL: "/staff/orders/:orderId",
  STAFF_PRODUCTS: "/staff/products",
  STAFF_BRANDS: "/staff/brands",
  STAFF_USERS: "/staff/users",
  // Hidden temporarily — can be unblocked when needed
  // STAFF_PAYMENTS: "/staff/payments",
  // STAFF_FEEDBACK: "/staff/feedback",

  UNAUTHORIZED: "/401",
  FORBIDDEN: "/403",
  SERVER_ERROR: "/500",
  SERVICE_UNAVAILABLE: "/503",
  GATEWAY_TIMEOUT: "/504",
} as const;
